CREATE TYPE "UserRole" AS ENUM (
  'user',
  'admin'
);

CREATE TYPE "UserStatus" AS ENUM (
  'active',
  'suspended'
);

CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255),
  "full_name" varchar(255) NOT NULL,
  "profile_image_url" varchar(500),
  "bio" text,
  "role" "UserRole" NOT NULL DEFAULT 'user',
  "status" "UserStatus" NOT NULL DEFAULT 'active',
  "google_provider_id" varchar(255) UNIQUE,
  "apple_provider_id" varchar(255) UNIQUE,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "Categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE "Events" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "description" text NOT NULL,
  "organizer_name" varchar(255) NOT NULL,
  "event_time" timestamp NOT NULL,
  "location_name" varchar(255) NOT NULL,
  "location_lat" decimal(10,8),
  "location_lon" decimal(11,8),
  "banner_image_url" varchar(500),
  "category_id" int,
  "created_by_admin_id" int,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "EventRegistrations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "event_id" int NOT NULL,
  "registered_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "EventReviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "event_id" int NOT NULL,
  "rating" int NOT NULL,
  "comment_text" text,
  "is_visible" boolean NOT NULL DEFAULT true,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "Badges" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" text NOT NULL,
  "icon_url" varchar(500) NOT NULL,
  "criteria_key" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "UserBadges" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "badge_id" int NOT NULL,
  "earned_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE UNIQUE INDEX ON "EventRegistrations" ("user_id", "event_id");

CREATE UNIQUE INDEX ON "EventReviews" ("user_id", "event_id");

CREATE UNIQUE INDEX ON "UserBadges" ("user_id", "badge_id");

COMMENT ON COLUMN "Users"."id" IS 'Unique user identifier';

COMMENT ON COLUMN "Users"."email" IS 'User s login email';

COMMENT ON COLUMN "Users"."password_hash" IS 'Hashed password; NULL if only social login';

COMMENT ON COLUMN "Users"."full_name" IS 'User s display name';

COMMENT ON COLUMN "Users"."profile_image_url" IS 'URL to user s avatar';

COMMENT ON COLUMN "Users"."role" IS 'Role for access control';

COMMENT ON COLUMN "Users"."status" IS 'For admin to manage users';

COMMENT ON COLUMN "Users"."google_provider_id" IS 'For Google Sign-In';

COMMENT ON COLUMN "Users"."apple_provider_id" IS 'For Apple Sign-In';

COMMENT ON COLUMN "Users"."created_at" IS 'Timestamp of registration';

COMMENT ON COLUMN "Categories"."id" IS 'Unique category identifier';

COMMENT ON COLUMN "Categories"."name" IS 'Category name, e.g., "Music", "Tech", "Art"';

COMMENT ON COLUMN "Events"."id" IS 'Unique event identifier';

COMMENT ON COLUMN "Events"."title" IS 'Name of the event';

COMMENT ON COLUMN "Events"."description" IS 'Detailed event description';

COMMENT ON COLUMN "Events"."organizer_name" IS 'Name of the event host';

COMMENT ON COLUMN "Events"."event_time" IS 'Start date and time of the event';

COMMENT ON COLUMN "Events"."location_name" IS 'Human-readable location';

COMMENT ON COLUMN "Events"."location_lat" IS 'Latitude for MapKit integration';

COMMENT ON COLUMN "Events"."location_lon" IS 'Longitude for MapKit integration';

COMMENT ON COLUMN "Events"."category_id" IS 'Links event to a category for filtering';

COMMENT ON COLUMN "Events"."created_by_admin_id" IS 'Admin who created the event';

COMMENT ON COLUMN "Events"."created_at" IS 'Timestamp of event creation';

COMMENT ON COLUMN "EventRegistrations"."id" IS 'Unique registration identifier';

COMMENT ON COLUMN "EventRegistrations"."user_id" IS 'The user who is attending';

COMMENT ON COLUMN "EventRegistrations"."event_id" IS 'The event being attended';

COMMENT ON COLUMN "EventReviews"."id" IS 'Unique review identifier';

COMMENT ON COLUMN "EventReviews"."user_id" IS 'The user who wrote the review';

COMMENT ON COLUMN "EventReviews"."event_id" IS 'The event being reviewed';

COMMENT ON COLUMN "EventReviews"."rating" IS 'Star rating from 1 to 5';

COMMENT ON COLUMN "EventReviews"."is_visible" IS 'Toggled by admin for moderation';

COMMENT ON COLUMN "Badges"."id" IS 'Unique badge identifier';

COMMENT ON COLUMN "Badges"."name" IS 'Name of the badge, e.g., "First Event"';

COMMENT ON COLUMN "Badges"."description" IS 'How to earn the badge';

COMMENT ON COLUMN "Badges"."icon_url" IS 'URL to the badge s image';

COMMENT ON COLUMN "Badges"."criteria_key" IS 'Key for backend logic, e.g., "EVENT_COUNT_5"';

COMMENT ON COLUMN "UserBadges"."id" IS 'Unique earned-badge identifier';

COMMENT ON COLUMN "UserBadges"."user_id" IS 'The user who earned the badge';

COMMENT ON COLUMN "UserBadges"."badge_id" IS 'The badge that was earned';

COMMENT ON COLUMN "UserBadges"."earned_at" IS 'When the badge was awarded';

ALTER TABLE "Events" ADD FOREIGN KEY ("category_id") REFERENCES "Categories" ("id") ON DELETE SET NULL;

ALTER TABLE "Events" ADD FOREIGN KEY ("created_by_admin_id") REFERENCES "Users" ("id");

ALTER TABLE "EventRegistrations" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id") ON DELETE CASCADE;

ALTER TABLE "EventRegistrations" ADD FOREIGN KEY ("event_id") REFERENCES "Events" ("id") ON DELETE CASCADE;

ALTER TABLE "EventReviews" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id") ON DELETE CASCADE;

ALTER TABLE "EventReviews" ADD FOREIGN KEY ("event_id") REFERENCES "Events" ("id") ON DELETE CASCADE;

ALTER TABLE "UserBadges" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id") ON DELETE CASCADE;

ALTER TABLE "UserBadges" ADD FOREIGN KEY ("badge_id") REFERENCES "Badges" ("id") ON DELETE CASCADE;
